name: Update LeetCode Streak

on:
  schedule:
    - cron: "0 0 * * *"  # runs every day at midnight UTC
  workflow_dispatch:      # allows manual run from Actions tab

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"

      - name: Install dependencies
        run: pip install requests

      - name: Run updater script
        env:
          LEETCODE_USERNAME: ${{ secrets.LEETCODE_USERNAME }}
        run: python update_leetcode.py
      
      - name: Debug LeetCode data
        run: |
          echo "=== Debugging LeetCode Submissions ==="
          python - <<'EOF'
          from update_leetcode import get_recent_submissions
          subs = get_recent_submissions()
          for s in subs:
              print(s)
          EOF


      - name: Commit changes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add README.md
          git commit -m "Update LeetCode streak" || echo "No changes to commit"
          git push https://x-access-token:${GITHUB_TOKEN}@github.com/${{ github.repository }}.git
